// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripCraft.Infrastructure.Persistence;

#nullable disable

namespace TripCraft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925202645_AddAgentWorkflows")]
    partial class AddAgentWorkflows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TripCraft.Application.Common.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Trips.Attraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<decimal>("EntryFeeLkr")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("entry_fee_lkr");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attractions");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_attractions_city");

                    b.ToTable("attractions", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Trips.Itinerary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("generated_by");

                    b.Property<Guid>("TripRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_request_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_itineraries");

                    b.HasIndex("TripRequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_itineraries_trip_request_id");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Trips.ItineraryDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.Property<Guid>("ItineraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_itinerary_days");

                    b.HasIndex("ItineraryId", "DayNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_itinerary_days_itinerary_id_day_number");

                    b.ToTable("itinerary_days", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Trips.ItineraryStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time")
                        .HasColumnName("arrival_time");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("attraction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItineraryDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("itinerary_day_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_itinerary_stops");

                    b.HasIndex("AttractionId")
                        .HasDatabaseName("ix_itinerary_stops_attraction_id");

                    b.HasIndex("ItineraryDayId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_itinerary_stops_itinerary_day_id_sequence");

                    b.ToTable("itinerary_stops", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Trips.Tourist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("PassportNumberMasked")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passport_number_masked");

                    b.Property<string>("PassportPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passport_photo_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tourists");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_tourists_user_id");

                    b.ToTable("tourists", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Trips.TripRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BudgetUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("budget_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<int>("Pax")
                        .HasColumnType("integer")
                        .HasColumnName("pax");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TouristId")
                        .HasColumnType("uuid")
                        .HasColumnName("tourist_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trip_requests");

                    b.HasIndex("TouristId")
                        .HasDatabaseName("ix_trip_requests_tourist_id");

                    b.HasIndex("Status", "StartDate")
                        .HasDatabaseName("ix_trip_requests_status_start_date");

                    b.ToTable("trip_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_trip_requests_end_after_start", "end_date >= start_date");

                            t.HasCheckConstraint("ck_trip_requests_pax_positive", "pax > 0");
                        });
                });

            modelBuilder.Entity("TripCraft.Application.Workflows.AgentStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_summary");

                    b.Property<string>("OutputSummary")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_summary");

                    b.Property<int>("Retries")
                        .HasColumnType("integer")
                        .HasColumnName("retries");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<string>("ToolName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationResult")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_result");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_steps");

                    b.HasIndex("WorkflowId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("ix_agent_steps_workflow_id_step_no");

                    b.ToTable("agent_steps", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Workflows.AgentWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_step");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<string>("FinalOutcome")
                        .HasColumnType("jsonb")
                        .HasColumnName("final_outcome");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_request_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_result");

                    b.HasKey("Id")
                        .HasName("pk_agent_workflows");

                    b.HasIndex("TripRequestId")
                        .HasDatabaseName("ix_agent_workflows_trip_request_id");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_agent_workflows_status_started_at");

                    b.ToTable("agent_workflows", (string)null);
                });

            modelBuilder.Entity("TripCraft.Application.Workflows.External.CityDistance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("distance_km");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("from_city");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("to_city");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_city_distances");

                    b.HasIndex("FromCity", "ToCity")
                        .IsUnique()
                        .HasDatabaseName("ix_city_distances_from_city_to_city");

                    b.ToTable("city_distances", null, t =>
                        {
                            t.HasCheckConstraint("ck_city_distances_positive", "distance_km > 0 AND duration_minutes > 0");
                        });
                });

            modelBuilder.Entity("TripCraft.Application.Trips.Itinerary", b =>
                {
                    b.HasOne("TripCraft.Application.Trips.TripRequest", "TripRequest")
                        .WithMany()
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itineraries_trip_requests_trip_request_id");

                    b.Navigation("TripRequest");
                });

            modelBuilder.Entity("TripCraft.Application.Trips.ItineraryDay", b =>
                {
                    b.HasOne("TripCraft.Application.Trips.Itinerary", null)
                        .WithMany("Days")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_days_itineraries_itinerary_id");
                });

            modelBuilder.Entity("TripCraft.Application.Trips.ItineraryStop", b =>
                {
                    b.HasOne("TripCraft.Application.Trips.Attraction", "Attraction")
                        .WithMany()
                        .HasForeignKey("AttractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_stops_attractions_attraction_id");

                    b.HasOne("TripCraft.Application.Trips.ItineraryDay", null)
                        .WithMany("Stops")
                        .HasForeignKey("ItineraryDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_stops_itinerary_days_itinerary_day_id");

                    b.Navigation("Attraction");
                });

            modelBuilder.Entity("TripCraft.Application.Trips.Tourist", b =>
                {
                    b.HasOne("TripCraft.Application.Identity.User", null)
                        .WithOne()
                        .HasForeignKey("TripCraft.Application.Trips.Tourist", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tourists_users_user_id");
                });

            modelBuilder.Entity("TripCraft.Application.Trips.TripRequest", b =>
                {
                    b.HasOne("TripCraft.Application.Trips.Tourist", "Tourist")
                        .WithMany()
                        .HasForeignKey("TouristId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_requests_tourists_tourist_id");

                    b.Navigation("Tourist");
                });

            modelBuilder.Entity("TripCraft.Application.Workflows.AgentStep", b =>
                {
                    b.HasOne("TripCraft.Application.Workflows.AgentWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_steps_agent_workflows_workflow_id");
                });

            modelBuilder.Entity("TripCraft.Application.Workflows.AgentWorkflow", b =>
                {
                    b.HasOne("TripCraft.Application.Trips.TripRequest", null)
                        .WithMany()
                        .HasForeignKey("TripRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_workflows_trip_requests_trip_request_id");
                });

            modelBuilder.Entity("TripCraft.Application.Trips.Itinerary", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("TripCraft.Application.Trips.ItineraryDay", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
